/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.awt.BorderLayout;

/**
 *
 * @author unwir
 */
public class IniciarSesion extends javax.swing.JFrame {
    private GestionUsuario gestion;
    private fondo fondo2;
    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        initComponents();
        gestion = GestionUsuario.getInstancia();
        cargarFondo();
    }
    
       private void cargarFondo(){
        fondo2 = new fondo("/images/fondo3.png");
        fondo2.setSize(panelFondin.getWidth(), panelFondin.getHeight());
        panelFondin.setLayout(new BorderLayout());
        panelFondin.add(fondo2, BorderLayout.CENTER);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearUsuario1 = new proyecto.crearUsuario();
        panelFondin = new javax.swing.JPanel();
        nomUsuario = new javax.swing.JTextField();
        passWord = new javax.swing.JPasswordField();
        iniciarSesion = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        panelFondin.setMaximumSize(new java.awt.Dimension(800, 500));
        panelFondin.setMinimumSize(new java.awt.Dimension(800, 500));
        panelFondin.setPreferredSize(new java.awt.Dimension(800, 500));
        panelFondin.setLayout(null);

        nomUsuario.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        nomUsuario.setBorder(null);
        nomUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomUsuarioActionPerformed(evt);
            }
        });
        panelFondin.add(nomUsuario);
        nomUsuario.setBounds(370, 180, 230, 20);

        passWord.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        passWord.setBorder(null);
        passWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passWordActionPerformed(evt);
            }
        });
        panelFondin.add(passWord);
        passWord.setBounds(370, 260, 230, 20);

        iniciarSesion.setBackground(new java.awt.Color(255, 0, 51));
        iniciarSesion.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        iniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        iniciarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        iniciarSesion.setBorderPainted(false);
        iniciarSesion.setContentAreaFilled(false);
        iniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionActionPerformed(evt);
            }
        });
        panelFondin.add(iniciarSesion);
        iniciarSesion.setBounds(220, 330, 170, 90);

        salir.setBackground(new java.awt.Color(255, 0, 51));
        salir.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        panelFondin.add(salir);
        salir.setBounds(420, 330, 170, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/INICIOSESION.png"))); // NOI18N
        panelFondin.add(jLabel4);
        jLabel4.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomUsuarioActionPerformed

    private void iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionActionPerformed
        // TODO add your handling code here:
        String nomU = nomUsuario.getText();
        String passW = new String(passWord.getPassword());
       
            if(!gestion.loginJugador(nomU, passW)){
               javax.swing.JOptionPane.showMessageDialog(null, "La contraseña es incorrecta");
            }else{
                gestion.loginJugador(nomU, passW);
                javax.swing.JOptionPane.showMessageDialog(null, "Inicio de Sesion exitosa!");
                System.out.println("Usuario Actual: " + gestion.getJugadorActual());
                menuPrincipal1 a = new menuPrincipal1();
                a.setVisible(true);
                this.dispose();
           } 
    
    }//GEN-LAST:event_iniciarSesionActionPerformed

    private void passWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passWordActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        menuPrincipal1 a = new menuPrincipal1();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private proyecto.crearUsuario crearUsuario1;
    private javax.swing.JButton iniciarSesion;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nomUsuario;
    private javax.swing.JPanel panelFondin;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
