package proyecto;

import javax.swing.JOptionPane;
import java.awt.BorderLayout;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hnleo
 */
public class MiPerfil extends javax.swing.JFrame {
    
    GestionUsuario gestion;

    /**
     * Creates new form MiPerfil
     */
    public MiPerfil() {
        initComponents();
        gestion = GestionUsuario.getInstancia();
        nombreLabel.setText(gestion.getJugadorActual());
        System.out.println(gestion.toString());
     
        jLabel4.setText(String.valueOf(gestion.getJugador1().getPuntaje()));
        jLabel3.setText(String.valueOf(gestion.getJugador1().getPartidasHeroe()));
        jLabel2.setText(String.valueOf(gestion.getJugador1().getPartidasVillano()));
        
        jTextArea1.setText(gestion.getJugador1().getLogeo());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPadre = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        cambiarPass = new javax.swing.JButton();
        eliminarCuenta = new javax.swing.JButton();
        regresarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        panelPadre.setMaximumSize(new java.awt.Dimension(800, 500));
        panelPadre.setMinimumSize(new java.awt.Dimension(800, 500));
        panelPadre.setOpaque(false);
        panelPadre.setPreferredSize(new java.awt.Dimension(800, 500));
        panelPadre.setLayout(null);

        nombreLabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        nombreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreLabel.setText("Nombre");
        panelPadre.add(nombreLabel);
        nombreLabel.setBounds(120, 90, 136, 34);

        cambiarPass.setBackground(new java.awt.Color(255, 0, 51));
        cambiarPass.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        cambiarPass.setForeground(new java.awt.Color(255, 255, 255));
        cambiarPass.setAlignmentY(0.0F);
        cambiarPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        cambiarPass.setBorderPainted(false);
        cambiarPass.setContentAreaFilled(false);
        cambiarPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cambiarPass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cambiarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarPassActionPerformed(evt);
            }
        });
        panelPadre.add(cambiarPass);
        cambiarPass.setBounds(560, 70, 170, 90);

        eliminarCuenta.setBackground(new java.awt.Color(255, 0, 51));
        eliminarCuenta.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        eliminarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        eliminarCuenta.setAlignmentY(0.0F);
        eliminarCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        eliminarCuenta.setBorderPainted(false);
        eliminarCuenta.setContentAreaFilled(false);
        eliminarCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarCuenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCuentaActionPerformed(evt);
            }
        });
        panelPadre.add(eliminarCuenta);
        eliminarCuenta.setBounds(560, 180, 170, 90);

        regresarButton.setBackground(new java.awt.Color(255, 0, 51));
        regresarButton.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        regresarButton.setForeground(new java.awt.Color(255, 255, 255));
        regresarButton.setAlignmentY(0.0F);
        regresarButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        regresarButton.setBorderPainted(false);
        regresarButton.setContentAreaFilled(false);
        regresarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });
        panelPadre.add(regresarButton);
        regresarButton.setBounds(590, 430, 138, 42);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("jLabel2");
        panelPadre.add(jLabel2);
        jLabel2.setBounds(410, 224, 30, 40);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("jLabel2");
        panelPadre.add(jLabel3);
        jLabel3.setBounds(420, 284, 41, 40);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setText("jLabel2");
        panelPadre.add(jLabel4);
        jLabel4.setBounds(240, 160, 30, 50);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        panelPadre.add(jScrollPane1);
        jScrollPane1.setBounds(80, 370, 470, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MIPERFIL.png"))); // NOI18N
        panelPadre.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cambiarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarPassActionPerformed

        String inputPass = JOptionPane.showInputDialog("Introduzca su contraseña actual");
        if (gestion.verificarLaPassWord(inputPass)) {
              nuevaPass nueva = new nuevaPass();
              nueva.setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Contraseña incorrecta.");

        }
    }//GEN-LAST:event_cambiarPassActionPerformed

    private void eliminarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCuentaActionPerformed
        // TODO add your handling code here:
        String inputPass = JOptionPane.showInputDialog("Introduzca su contraseña para confirmar");
        if (gestion.verificarLaPassWord(inputPass)) {
            gestion.eliminarUsuario(gestion.getJugadorActual());
            System.out.println(gestion.toString());
            javax.swing.JOptionPane.showMessageDialog(null, "USUARIO ELIMINADO CON EXITO!");
            menuPrincipal1 menu = new menuPrincipal1();
            menu.setVisible(true);
            this.dispose();
            System.out.println(gestion.toString());
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "ERROR, Contraseña incorrecta");

        }
    }//GEN-LAST:event_eliminarCuentaActionPerformed

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        menuPrincipal1 menu = new menuPrincipal1();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarPass;
    private javax.swing.JButton eliminarCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JPanel panelPadre;
    private javax.swing.JButton regresarButton;
    // End of variables declaration//GEN-END:variables
}
